name: picture_reminder
description: An app reminding you to take a picture of your day.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  intl: ^0.18.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true